//API REST de usuarios
// Teste da API REST de usuários
@baseURL = http://localhost:3000/api/usuarios
###
# @prompt senha

POST {{baseURL}}
Content-Type: application/json

{
    "nome": "Iago Rossan",
    "email": "iagorossan@fatec.gov.br",
    "senha": "{{senha}}"
}

###
# @prompt senha
POST {{baseURL}}/login
Content-Type: application/json

{
    "email": "iagorossan@fatec.gov.br",
    "senha": "{{senha}}"
}